version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: dev-burguer-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
